version: 2.1

executors:
  node-environment:
    docker:
      - image: "circleci/node:12.6.0"
    # working_directory: /tmp

jobs:
  install-dependencies:
    executor: node-environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: install-dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - '*'
  test:
    executor: node-environment
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: run-test
          command: yarn test

  release:
    executor: node-environment
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: release
          command: yarn semantic-release || true

workflows:
  version: 2
  Test_and_release:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - release:
          requires:
            - install-dependencies
