version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  gcp-gcr: circleci/gcp-gcr@0.7.1

references:
  workspace_root: &workspace_root ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  node-environment:
    docker:
      - image: "circleci/node:12.6.0"
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: node-environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: install-dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  test:
    executor: node-environment
    steps:
      - *attach_workspace
      - run:
          name: run-test
          command: yarn test
      - codecov/upload:
          file: coverage/*.json

  release:
    executor: node-environment
    steps:
      - *attach_workspace
      - run:
          name: release
          command: yarn semantic-release || true

  build-and-push:
    executor: gcp-gcr/default
    steps:
      - *attach_workspace
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: njausteve-resume-v2
          registry-url: gcr.io
          tag: gcr.io/${GOOGLE_PROJECT_ID}/njausteve-resume-v2:$CIRCLE_SHA1
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: njausteve-resume-v2
          registry-url: gcr.io
          tag: gcr.io/${GOOGLE_PROJECT_ID}/njausteve-resume-v2:$CIRCLE_SHA1
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  version: 2
  Test_and_release:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - release:
          requires:
            - install-dependencies
      - build-and-push:
           requires:
             - test
