version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

references:
  workspace_root: &workspace_root ~/project
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

executors:
  node-environment:
    docker:
      - image: "circleci/node:12.6.0"
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: node-environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: install-dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .
  test:
    executor: node-environment
    steps:
      - *attach_workspace
      - run:
          name: run-test
          command: yarn test
      - codecov/upload:
          file: ~/project/coverage/coverage-final.json

  release:
    executor: node-environment
    steps:
      - *attach_workspace
      - run:
          name: release
          command: yarn semantic-release || true

workflows:
  version: 2
  Test_and_release:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - release:
          requires:
            - install-dependencies
